<a href="https://colab.research.google.com/github/planet-c-am/Project-no-1/blob/main/Section%20A%3AData%20Import%20%26%20Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Section A : Data Import & Preprocessing

In [9]:
# @title 1.Load the dataset and display its first 10 rows.
# step-1: import require library function
import numpy as np
import pandas as pd

# step-2: load data file
df=pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vRNjLy1z3pmGHGjiRjN1mmNEYIjebkBlhav-5mgd9OCGGDwFnL_LPRXvoBThu-JPDZVINbYb1I6Yp3I/pub?gid=961875835&single=true&output=csv')

# step-3: display first 10 rows
df.head(10)
#display(df.head(10))

             DateTime  Junction  Vehicles           ID
0  2015-11-01 0:00:00         1        15  20151101001
1  2015-11-01 1:00:00         1        13  20151101011
2  2015-11-01 2:00:00         1        10  20151101021
3  2015-11-01 3:00:00         1         7  20151101031
4  2015-11-01 4:00:00         1         9  20151101041
5  2015-11-01 5:00:00         1         6  20151101051
6  2015-11-01 6:00:00         1         9  20151101061
7  2015-11-01 7:00:00         1         8  20151101071
8  2015-11-01 8:00:00         1        11  20151101081
9  2015-11-01 9:00:00         1        12  20151101091

In [8]:
# @title 2.Identify missing values and handle them appropriately
# step-1: import require library function
import numpy as np
import pandas as pd

# step-2: load data file
df=pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vRNjLy1z3pmGHGjiRjN1mmNEYIjebkBlhav-5mgd9OCGGDwFnL_LPRXvoBThu-JPDZVINbYb1I6Yp3I/pub?gid=961875835&single=true&output=csv')
df.isnull().sum()

DateTime    0
Junction    0
Vehicles    0
ID          0
dtype: int64

In [7]:
# @title 3.Convert the date_time column into multiple features: Hour, Day of Week, Weekend indicator
# step-1: import require library function
import numpy as np
import pandas as pd

# step-2: load data file
df=pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vRNjLy1z3pmGHGjiRjN1mmNEYIjebkBlhav-5mgd9OCGGDwFnL_LPRXvoBThu-JPDZVINbYb1I6Yp3I/pub?gid=961875835&single=true&output=csv')

# step-3: logical function
df['DateTime']=pd.to_datetime(df['DateTime'])
# Hour
df['Hour']=df['DateTime'].dt.hour
# Day of Week(Monday=0, sunday=6)
df['DayofWeek']=df['DateTime'].dt.dayofweek
# Weekend indicator
df['IsWeekend']=df['DayofWeek'].apply(lambda x:1 if x in[6]  else 0)


# Weekend indicator(Bangladesh friday-4, saturday-5)
#df['IsWeekend']=df['DayofWeek'].apply(lambda x:1 if x in [4,5] else 0)

# step-4: show first 10 rows
print(df.head(10))

             DateTime  Junction  Vehicles           ID  Hour  DayofWeek  \
0 2015-11-01 00:00:00         1        15  20151101001     0          6
1 2015-11-01 01:00:00         1        13  20151101011     1          6
2 2015-11-01 02:00:00         1        10  20151101021     2          6
3 2015-11-01 03:00:00         1         7  20151101031     3          6
4 2015-11-01 04:00:00         1         9  20151101041     4          6
5 2015-11-01 05:00:00         1         6  20151101051     5          6
6 2015-11-01 06:00:00         1         9  20151101061     6          6
7 2015-11-01 07:00:00         1         8  20151101071     7          6
8 2015-11-01 08:00:00         1        11  20151101081     8          6
9 2015-11-01 09:00:00         1        12  20151101091     9          6

   IsWeekend
0          1
1          1
2          1
3          1
4          1
5          1
6          1
7          1
8          1
9          1

In [6]:
# @title  4.Normalize numerical features if required
# step-1: import require library function
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# step-2: load data file
df=pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vRNjLy1z3pmGHGjiRjN1mmNEYIjebkBlhav-5mgd9OCGGDwFnL_LPRXvoBThu-JPDZVINbYb1I6Yp3I/pub?gid=961875835&single=true&output=csv')

# step-3: logical function
df['DateTime']=pd.to_datetime(df['DateTime'])
# Hour
df['Hour']=df['DateTime'].dt.hour
# Day of Week(Monday=0, sunday=6)
df['DayofWeek']=df['DateTime'].dt.dayofweek
# Weekend indicator
df['IsWeekend']=df['DayofWeek'].apply(lambda x:1 if x in [6] else 0)


# Weekend indicator(Bangladesh Friday=4, saturday=5)
#df['IsWeekend']=df['DayofWeek'].apply(lambda x:1 if x in [4,5] else 0)

# step-4: Normalize numerical feature(Hour, DayofWeek only)
scaler=MinMaxScaler()
df[['Hour', 'DayofWeek']]=scaler.fit_transform(df[['Hour', 'DayofWeek']])

# step-5: show first 10 rows
print(df.head(10))

             DateTime  Junction  Vehicles           ID      Hour  DayofWeek  \
0 2015-11-01 00:00:00         1        15  20151101001  0.000000        1.0
1 2015-11-01 01:00:00         1        13  20151101011  0.043478        1.0
2 2015-11-01 02:00:00         1        10  20151101021  0.086957        1.0
3 2015-11-01 03:00:00         1         7  20151101031  0.130435        1.0
4 2015-11-01 04:00:00         1         9  20151101041  0.173913        1.0
5 2015-11-01 05:00:00         1         6  20151101051  0.217391        1.0
6 2015-11-01 06:00:00         1         9  20151101061  0.260870        1.0
7 2015-11-01 07:00:00         1         8  20151101071  0.304348        1.0
8 2015-11-01 08:00:00         1        11  20151101081  0.347826        1.0
9 2015-11-01 09:00:00         1        12  20151101091  0.391304        1.0

   IsWeekend
0          1
1          1
2          1
3          1
4          1
5          1
6          1
7          1
8          1
9          1